### PR TITLE
Loss Properties

### PR DESCRIPTION
**Pull request by Evizero**
So I went through the literature again to finish this up. I have implemented the fallback methods (and tests) so far.

I created a table of the properties of the losses we have. I am not too confident about correctness for all entries however. So if someone feels like double checking some be my guest!

| Name | isminimizable | isdifferentiable | isconvex | isnemitski | islipschitzcont | islocallylipshitzcont | isclipable | ismarginbased | isclasscalibrated | isdistancebased | issymmetric | isfishercons | isunivfishercons |
|------------------------|---------------|------------------|----------|------------|-----------------|-----------------------|------------|---------------|-------------------|-----------------|-------------|--------------|------------------|
| LogitMarginLoss() | TRUE | TRUE | TRUE | TRUE | TRUE | TRUE | FALSE | TRUE | TRUE | FALSE | FALSE | TRUE | TRUE |
| HingeLoss() | TRUE | FALSE | TRUE | TRUE | TRUE | TRUE | TRUE | TRUE | TRUE | FALSE | FALSE | TRUE | FALSE |
| L2HingeLoss() | TRUE | TRUE | TRUE | TRUE | FALSE | TRUE | TRUE | TRUE | TRUE | FALSE | FALSE | TRUE | TRUE |
| L1DistLoss() | TRUE | FALSE | TRUE | TRUE | TRUE | TRUE | TRUE | FALSE | FALSE | TRUE | TRUE |  |  |
| L2DistLoss() | TRUE | TRUE | TRUE | TRUE | FALSE | TRUE | TRUE | FALSE | FALSE | TRUE | TRUE |  |  |
| LPDistLoss(p) | TRUE | p>1 | p>=1 | TRUE | p=1 | p>=1 (fallback?) | TRUE | FALSE | FALSE | TRUE | TRUE |  |  |
| LogitDistLoss() | TRUE | TRUE | TRUE | TRUE | TRUE | TRUE | TRUE | FALSE | FALSE | TRUE | TRUE |  |  |
| HuberLoss(a) | TRUE | TRUE | TRUE | TRUE | TRUE | TRUE | TRUE | FALSE | FALSE | TRUE | TRUE |  |  |
| EpsilonInsLoss(e) | TRUE | FALSE | TRUE | TRUE | TRUE | TRUE | TRUE | FALSE | FALSE | TRUE | TRUE |  |  |
| PinballLoss(e) | TRUE |  | TRUE | TRUE | e >0 | TRUE | e=1/2 | FALSE | FALSE | TRUE | e=1/2 |  |  |
| SmoothedL1HingeLoss(e) | TRUE | e>0 | TRUE | TRUE | TRUE | TRUE | TRUE | TRUE | TRUE | FALSE | FALSE |  |  |
| ZeroOneLoss() | TRUE | FALSE | FALSE | TRUE |  |  | TRUE | TRUE | TRUE | FALSE | FALSE |  |  |
| L2EpsilonInsLoss(e) | TRUE | TRUE | TRUE | TRUE | FALSE | TRUE | TRUE | FALSE | FALSE | TRUE | TRUE |  |  |
| ModifiedHuberLoss(e) | TRUE | TRUE | TRUE | TRUE | TRUE | TRUE | TRUE | TRUE | TRUE | FALSE | FALSE |  |  |
| PerceptronLoss() | TRUE | FALSE | TRUE | TRUE | TRUE | TRUE | TRUE | TRUE | FALSE? | FALSE | FALSE |  |  |
| PeriodicLoss() |  |  |  |  |  |  |  |  |  |  |  |  |  |

### CODE REVIEW

**Comment by Evizero** [comment]
I wonder. Should we put a properties table somewhere in the read the docs?

**Comment by tbreloff** [comment]
> Should we put a properties table somewhere in the read the docs?

That would be great.  Maybe also make a heatmap:

https://github.com/JuliaPlots/PlotDocs.jl/blob/master/src/PlotDocs.jl#L111-L140

https://juliaplots.github.io/supported/

**Comment by Evizero** [comment]
good idea

**Comment by Evizero** [comment]
Once the tests pass I'll merge and tag a release. I shall do the heatmap some other time.

**Pull request merged**
